import { NextResponse } from "next/server";
import { getProductsList } from "@/lib/c2c-scraper";
import { prisma } from "@/lib/prisma";
import { runBackgroundScrape } from "@/lib/background-worker";
import { initializeScrapeJob } from "@/lib/jobs";

export async function POST(req: Request) {
  try {
    const body = await req.json().catch(() => ({}));
    const limit = body.limit ? parseInt(body.limit, 10) : undefined;
    const clientJobId = body.jobId; // Pre-generated by client for resilience

    // 1. Maak de job DIRECT aan in de database, ZELFS voordat we de registry ophalen.
    // Dit voorkomt een race-conditie waarbij de user op F5 drukt en de job nog niet in de DB staat (waardoor de UI de job verwijdert).
    const job = await initializeScrapeJob(clientJobId, 0);

    if (!job) {
      return NextResponse.json(
        { message: "Job was cancelled before start", jobId: clientJobId },
        { status: 200 },
      );
    }

    // 2. Haal de registry op (dit duurt even, vandaar dat we de job hierboven al hebben opgeslagen)
    console.log("API Start: Fetching registry list...");
    let products;
    try {
      products = await getProductsList(limit);
      if (!products || products.length === 0) {
        await prisma.scrapeJob.update({ where: { id: job.id }, data: { status: "failed" } });
        return NextResponse.json(
          { error: "No products found in registry" },
          { status: 404 },
        );
      }
    } catch (err: any) {
      await prisma.scrapeJob.update({ where: { id: job.id }, data: { status: "failed" } });
      throw err;
    }

    // Update de job nu we weten hoeveel producten we hebben
    await prisma.scrapeJob.update({
      where: { id: job.id },
      data: { totalItems: products.length }
    });

    // 3. Insert all products as "pending"
    const productData = products.map((p) => ({
      jobId: job.id,
      slug: p.slug,
      productName: p.productName,
      company: p.company,
      level: p.level,
      standardVersion: p.standardVersion,
      status: "pending",
    }));

    await prisma.product.createMany({
      data: productData,
    });

    console.log(
      `API Start: Job ${job.id} created with ${products.length} pending items. Kicking off worker...`,
    );

    // 4. Fire and forget! (Run the heavy extraction in the background)
    // We intentionally DO NOT await this function.
    runBackgroundScrape(job.id).catch((err) => {
      console.error(`Background worker failed for Job ${job.id}:`, err);
    });

    // 5. Immediately return the jobId to the frontend
    return NextResponse.json(
      {
        message: "Scraping job started successfully in the background",
        jobId: job.id,
        totalExpected: products.length,
      },
      { status: 202 },
    );
  } catch (error: any) {
    console.error("API Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
