import { NextResponse } from 'next/server';
import { getProductsList } from '@/lib/c2c-scraper';
import { prisma } from '@/lib/prisma';
import { runBackgroundScrape } from '@/lib/background-worker';

export async function POST(req: Request) {
  try {
    const body = await req.json().catch(() => ({}));
    const limit = body.limit ? parseInt(body.limit, 10) : undefined;
    const clientJobId = body.jobId; // Pre-generated by client for resilience
    
    // 1. Fetch just the slugs/names from the registry
    console.log("API Start: Fetching registry list...");
    const products = await getProductsList(limit);
    
    if (!products || products.length === 0) {
      return NextResponse.json({ error: "No products found in registry" }, { status: 404 });
    }

    const now = new Date().toISOString();

    // 2. Create a new Job in the database
    // Use the client's ID if provided, otherwise let Prisma handle it
    const job = await prisma.scrapeJob.create({
      data: {
        id: clientJobId || undefined,
        totalItems: products.length,
        status: "running",
      }
    });

    // 3. Insert all products as "pending"
    const productData = products.map((p) => ({
      jobId: job.id,
      slug: p.slug,
      productName: p.productName,
      company: p.company,
      level: p.level,
      standardVersion: p.standardVersion,
      status: "pending",
    }));

    await prisma.product.createMany({
      data: productData
    });

    console.log(`API Start: Job ${job.id} created with ${products.length} pending items. Kicking off worker...`);

    // 4. Fire and forget! (Run the heavy extraction in the background)
    // We intentionally DO NOT await this function.
    runBackgroundScrape(job.id).catch((err) => {
      console.error(`Background worker failed for Job ${job.id}:`, err);
    });

    // 5. Immediately return the jobId to the frontend
    return NextResponse.json({ 
      message: "Scraping job started successfully in the background", 
      jobId: job.id,
      totalExpected: products.length
    }, { status: 202 });

  } catch (error: any) {
    console.error("API Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
